stages:
- stage: AspireTest
  condition: false
  displayName: 'Aspire Tests'
  dependsOn:
  - Build
  templateContext:
    inputs:
    - input: pipelineArtifact
      artifactName: $(os)$(subos)_$(arch)_build
      targetPath: $(Build.ArtifactStagingDirectory)/build
  strategy:
    matrix:
      windows-amd64:
        os: windows
        arch: amd64
        extension: .exe
      linux-amd64:
        os: linux
        arch: amd64
        extension: ''
      macos-amd64:
        os: darwin
        arch: amd64
        extension: ''
  steps:
  - checkout: aspire
  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      packageType: sdk
      includePreviewVersions: true
      useGlobalJson: true
      workingDirectory: $(Build.SourcesDirectory)/aspire
  - task: DotNetCoreCLI@2
    displayName: 'Run Aspire Tests'
    inputs:
      command: test
      projects: '$(Build.SourcesDirectory)/aspire/tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj'
    env:
      DcpPublisher__CliPath: $(Build.ArtifactStagingDirectory)/build/dcp$(extension)